# Generated by Django 4.2.5 on 2023-10-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auvi_file', models.FileField(upload_to='videoaudio/')),
            ],
        ),
    ]
